import {
  createId, todayISO, monthKey, formatCurrency, validateCategory, validateTransaction,
  computeMonthlySummary, aggregateExpenseByCategory, aggregateYearlyTotals,
  computeBudgetStatuses, buildBudgetAlert
} from './logic.js';

const STORAGE_KEY = 'spendwise-pro-week3-state';
const DEFAULT_STATE = {
  categories: [
    { id: 'cat-salary', name: 'Lương', type: 'income', icon: '💼' },
    { id: 'cat-bonus', name: 'Thưởng', type: 'income', icon: '🎉' },
    { id: 'cat-food', name: 'Ăn uống', type: 'expense', icon: '🍜' },
    { id: 'cat-transport', name: 'Di chuyển', type: 'expense', icon: '🛵' },
    { id: 'cat-bills', name: 'Hóa đơn', type: 'expense', icon: '💡' },
    { id: 'cat-entertainment', name: 'Giải trí', type: 'expense', icon: '🎬' }
  ],
  transactions: [
    { id: 'tx1', type: 'income', amount: 15000000, categoryId: 'cat-salary', date: '2026-05-01', description: 'Lương tháng 5' },
    { id: 'tx2', type: 'expense', amount: 450000, categoryId: 'cat-food', date: '2026-05-02', description: 'Ăn trưa cả tuần' },
    { id: 'tx3', type: 'expense', amount: 180000, categoryId: 'cat-transport', date: '2026-05-03', description: 'Đổ xăng' },
    { id: 'tx4', type: 'expense', amount: 600000, categoryId: 'cat-bills', date: '2026-05-05', description: 'Tiền điện nước' },
    { id: 'tx5', type: 'expense', amount: 320000, categoryId: 'cat-entertainment', date: '2026-05-10', description: 'Xem phim cuối tuần' },
    { id: 'tx6', type: 'income', amount: 2000000, categoryId: 'cat-bonus', date: '2026-04-20', description: 'Thưởng dự án' },
    { id: 'tx7', type: 'expense', amount: 300000, categoryId: 'cat-food', date: '2026-04-22', description: 'Đi chợ' },
    { id: 'tx8', type: 'expense', amount: 210000, categoryId: 'cat-transport', date: '2026-03-18', description: 'Gửi xe' }
  ],
  budgets: [
    { id: 'budget-food-2026-05', categoryId: 'cat-food', month: '2026-05', amount: 800000 },
    { id: 'budget-transport-2026-05', categoryId: 'cat-transport', month: '2026-05', amount: 400000 },
    { id: 'budget-bills-2026-05', categoryId: 'cat-bills', month: '2026-05', amount: 700000 }
  ],
  alerts: []
};
const els = {};
let state = loadState();
let editingCategoryId = null;
let editingTransactionId = null;
function loadState(){try{const raw=localStorage.getItem(STORAGE_KEY);if(!raw)return structuredClone(DEFAULT_STATE);const parsed=JSON.parse(raw);return {categories:parsed.categories||structuredClone(DEFAULT_STATE.categories),transactions:parsed.transactions||structuredClone(DEFAULT_STATE.transactions),budgets:parsed.budgets||structuredClone(DEFAULT_STATE.budgets),alerts:parsed.alerts||[]};}catch{return structuredClone(DEFAULT_STATE);}}
function saveState(){localStorage.setItem(STORAGE_KEY, JSON.stringify(state));}
function getSelectedMonth(){return els.reportMonth.value || monthKey(todayISO());}
function categoryById(id){return state.categories.find(item=>item.id===id);}
function bindElements(){Object.assign(els,{monthBadge:document.querySelector('#current-month-badge'),summaryIncome:document.querySelector('#summary-income'),summaryExpense:document.querySelector('#summary-expense'),summaryBalance:document.querySelector('#summary-balance'),summaryCount:document.querySelector('#summary-count'),budgetAlerts:document.querySelector('#budget-alerts'),categoryForm:document.querySelector('#category-form'),categoryName:document.querySelector('#category-name'),categoryType:document.querySelector('#category-type'),categoryIcon:document.querySelector('#category-icon'),categoryError:document.querySelector('#category-error'),categorySubmitText:document.querySelector('#category-submit-text'),categoryCancelBtn:document.querySelector('#category-cancel-edit'),categoryIncomeList:document.querySelector('#category-income-list'),categoryExpenseList:document.querySelector('#category-expense-list'),transactionForm:document.querySelector('#transaction-form'),transactionType:document.querySelector('#transaction-type'),transactionAmount:document.querySelector('#transaction-amount'),transactionCategory:document.querySelector('#transaction-category'),transactionDate:document.querySelector('#transaction-date'),transactionDescription:document.querySelector('#transaction-description'),transactionError:document.querySelector('#transaction-error'),transactionSubmitText:document.querySelector('#transaction-submit-text'),transactionCancelBtn:document.querySelector('#transaction-cancel-edit'),transactionList:document.querySelector('#transaction-list'),budgetForm:document.querySelector('#budget-form'),budgetCategory:document.querySelector('#budget-category'),budgetAmount:document.querySelector('#budget-amount'),budgetMonth:document.querySelector('#budget-month'),budgetError:document.querySelector('#budget-error'),budgetList:document.querySelector('#budget-list'),reportMonth:document.querySelector('#report-month'),reportYear:document.querySelector('#report-year'),pieLegend:document.querySelector('#pie-legend'),donutSvg:document.querySelector('#donut-chart'),yearlyChart:document.querySelector('#yearly-chart'),yearlyTable:document.querySelector('#yearly-table tbody'),resetBtn:document.querySelector('#reset-demo-data')});}
function renderSummary(){const month=getSelectedMonth();const summary=computeMonthlySummary(state.transactions, month);els.monthBadge.textContent=month;els.summaryIncome.textContent=formatCurrency(summary.income);els.summaryExpense.textContent=formatCurrency(summary.expense);els.summaryBalance.textContent=formatCurrency(summary.balance);els.summaryBalance.className=summary.balance>=0?'metric-value positive':'metric-value negative';els.summaryCount.textContent=`${summary.count} giao dịch`;}
function renderAlerts(){const month=getSelectedMonth();const statuses=computeBudgetStatuses(state.categories,state.transactions,state.budgets.filter(item=>item.month===month),month);if(!state.alerts.length && !statuses.some(item=>item.level!=='safe')){els.budgetAlerts.innerHTML='<div class="empty-state">Chưa có cảnh báo hạn mức trong tháng đang xem.</div>';return;}const cards=[];state.alerts.slice(-3).reverse().forEach(item=>cards.push(`<div class="alert-card ${item.level}">${item.text}</div>`));statuses.filter(item=>item.level!=='safe').forEach(item=>{const label=item.level==='danger'?'Vượt hạn mức':item.level==='critical'?'Cận mức nguy hiểm':'Sắp chạm hạn mức';cards.push(`<div class="alert-card ${item.level}">${item.icon} ${item.categoryName}: ${label} (${item.usage}%)</div>`);});els.budgetAlerts.innerHTML=cards.join('');}
function syncCategorySelectors(){const type=els.transactionType.value;const categories=state.categories.filter(item=>item.type===type);els.transactionCategory.innerHTML='<option value="">-- Chọn danh mục --</option>'+categories.map(item=>`<option value="${item.id}">${item.icon} ${item.name}</option>`).join('');const expenseCategories=state.categories.filter(item=>item.type==='expense');els.budgetCategory.innerHTML='<option value="">-- Chọn danh mục chi --</option>'+expenseCategories.map(item=>`<option value="${item.id}">${item.icon} ${item.name}</option>`).join('');}
function renderCategories(){const buildItems=type=>state.categories.filter(item=>item.type===type).map(item=>{const relatedTransactions=state.transactions.filter(tx=>tx.categoryId===item.id).length;return `<article class="list-card"><div><div class="list-title">${item.icon} ${item.name}</div><div class="list-meta">${type==='income'?'Danh mục thu':'Danh mục chi'} • ${relatedTransactions} giao dịch</div></div><div class="list-actions"><button class="secondary-btn" data-action="edit-category" data-id="${item.id}">Sửa</button><button class="danger-btn" data-action="delete-category" data-id="${item.id}">Xóa</button></div></article>`;}).join('');els.categoryIncomeList.innerHTML=buildItems('income')||'<div class="empty-state">Chưa có danh mục thu.</div>';els.categoryExpenseList.innerHTML=buildItems('expense')||'<div class="empty-state">Chưa có danh mục chi.</div>';syncCategorySelectors();}
function renderTransactions(){const month=getSelectedMonth();const items=state.transactions.filter(item=>monthKey(item.date)===month).sort((a,b)=>new Date(b.date)-new Date(a.date)).map(item=>{const category=categoryById(item.categoryId);return `<article class="list-card"><div><div class="list-title">${category?.icon||'❓'} ${category?.name||'Không xác định'} - <span class="${item.type==='income'?'positive':'negative'}">${formatCurrency(item.amount)}</span></div><div class="list-meta">${item.date} • ${item.description||'Không có mô tả'}</div></div><div class="list-actions"><button class="secondary-btn" data-action="edit-transaction" data-id="${item.id}">Sửa</button><button class="danger-btn" data-action="delete-transaction" data-id="${item.id}">Xóa</button></div></article>`;}).join('');els.transactionList.innerHTML=items||'<div class="empty-state">Chưa có giao dịch nào trong tháng đang xem.</div>';}
function renderBudgets(){const month=getSelectedMonth();els.budgetMonth.value=month;const rows=computeBudgetStatuses(state.categories,state.transactions,state.budgets.filter(item=>item.month===month),month).map(item=>`<article class="budget-row ${item.level}"><div class="budget-head"><strong>${item.icon} ${item.categoryName}</strong><span>${formatCurrency(item.spent)} / ${formatCurrency(item.limit)} (${item.usage}%)</span></div><div class="progress-track"><div class="progress-fill ${item.level==='safe'?'safe':item.level}" style="width:${Math.min(item.usage,100)}%"></div></div><div class="budget-actions"><span class="list-meta">Còn lại: ${formatCurrency(item.remaining)}</span><button class="danger-btn" data-action="delete-budget" data-id="${item.categoryId}" data-month="${month}">Xóa hạn mức</button></div></article>`).join('');els.budgetList.innerHTML=rows||'<div class="empty-state">Chưa thiết lập hạn mức cho tháng đang xem.</div>';}
function renderDonutChart(){const month=getSelectedMonth();const data=aggregateExpenseByCategory(state.transactions,state.categories,month);if(!data.length){els.donutSvg.innerHTML='<text x="110" y="110" text-anchor="middle" fill="#94a3b8">Không có dữ liệu</text>';els.pieLegend.innerHTML='<div class="empty-state">Tháng này chưa có giao dịch chi.</div>';return;}const colors=['#22c55e','#3b82f6','#f59e0b','#ef4444','#8b5cf6','#14b8a6'];let start=0;const radius=70;const center=110;const circumference=2*Math.PI*radius;const total=data.reduce((sum,item)=>sum+item.amount,0);const circles=data.map((item,index)=>{const ratio=item.amount/total;const dash=ratio*circumference;const gap=circumference-dash;const circle=`<circle r="${radius}" cx="${center}" cy="${center}" fill="transparent" stroke="${colors[index%colors.length]}" stroke-width="24" stroke-dasharray="${dash} ${gap}" stroke-dashoffset="${-start}" transform="rotate(-90 ${center} ${center})"></circle>`;start+=dash;return circle;}).join('');els.donutSvg.innerHTML=`${circles}<circle r="42" cx="${center}" cy="${center}" fill="#0f172a"></circle><text x="110" y="105" text-anchor="middle" fill="#e2e8f0" font-size="14">Tổng chi</text><text x="110" y="125" text-anchor="middle" fill="#f8fafc" font-size="16" font-weight="700">${Math.round(total/1000)}k</text>`;els.pieLegend.innerHTML=data.map((item,index)=>`<div class="legend-row"><span class="legend-bullet" style="background:${colors[index%colors.length]}"></span><span>${item.icon} ${item.name}</span><span>${formatCurrency(item.amount)} (${item.percent}%)</span></div>`).join('');}
function renderYearlyChart(){const year=Number(els.reportYear.value);const data=aggregateYearlyTotals(state.transactions,year);const maxValue=Math.max(1,...data.flatMap(item=>[item.income,item.expense]));els.yearlyChart.innerHTML=data.map(item=>{const incomeHeight=Math.max(6,Math.round((item.income/maxValue)*160));const expenseHeight=Math.max(6,Math.round((item.expense/maxValue)*160));return `<div class="bar-group" title="${item.label}: Thu ${formatCurrency(item.income)} | Chi ${formatCurrency(item.expense)} | Số dư ${formatCurrency(item.balance)}"><div class="bar income" style="height:${incomeHeight}px"></div><div class="bar expense ${item.balance<0?'highlight':''}" style="height:${expenseHeight}px"></div><div class="bar-label">${item.label}</div></div>`;}).join('');els.yearlyTable.innerHTML=data.map(item=>`<tr><td>${item.label}</td><td>${formatCurrency(item.income)}</td><td>${formatCurrency(item.expense)}</td><td class="${item.balance>=0?'positive':'negative'}">${formatCurrency(item.balance)}</td></tr>`).join('');}
function renderReports(){renderDonutChart();renderYearlyChart();}
function renderAll(){renderSummary();renderAlerts();renderCategories();renderTransactions();renderBudgets();renderReports();saveState();}
function resetCategoryForm(){editingCategoryId=null;els.categoryForm.reset();els.categoryType.value='expense';els.categoryIcon.value='🛒';els.categorySubmitText.textContent='Lưu danh mục';els.categoryCancelBtn.hidden=true;els.categoryError.textContent='';}
function resetTransactionForm(){editingTransactionId=null;els.transactionForm.reset();els.transactionType.value='expense';els.transactionDate.value=todayISO();syncCategorySelectors();els.transactionSubmitText.textContent='Lưu giao dịch';els.transactionCancelBtn.hidden=true;els.transactionError.textContent='';}
function handleCategorySubmit(event){event.preventDefault();const validation=validateCategory(state.categories,{name:els.categoryName.value,type:els.categoryType.value,icon:els.categoryIcon.value},editingCategoryId);if(!validation.ok){els.categoryError.textContent=validation.message;return;}if(editingCategoryId){state.categories=state.categories.map(item=>item.id===editingCategoryId?{...item,...validation.data}:item);}else{state.categories.push({id:createId('cat'),...validation.data});}resetCategoryForm();renderAll();}
function handleTransactionSubmit(event){event.preventDefault();const validation=validateTransaction(state.categories,{type:els.transactionType.value,amount:els.transactionAmount.value,categoryId:els.transactionCategory.value,date:els.transactionDate.value,description:els.transactionDescription.value});if(!validation.ok){els.transactionError.textContent=validation.message;return;}let tx;if(editingTransactionId){state.transactions=state.transactions.map(item=>item.id===editingTransactionId?{...item,...validation.data}:item);tx=state.transactions.find(item=>item.id===editingTransactionId);}else{tx={id:createId('tx'),...validation.data};state.transactions.push(tx);}const alert=buildBudgetAlert(tx,state.categories,state.budgets.filter(item=>item.month===monthKey(tx.date)),state.transactions,monthKey(tx.date));if(alert) state.alerts.push(alert);resetTransactionForm();renderAll();}
function handleBudgetSubmit(event){event.preventDefault();const categoryId=els.budgetCategory.value;const amount=Number(els.budgetAmount.value);const month=els.budgetMonth.value;if(!categoryId){els.budgetError.textContent='Vui lòng chọn danh mục chi';return;}if(!(amount>0)){els.budgetError.textContent='Hạn mức phải lớn hơn 0 ₫';return;}const existing=state.budgets.find(item=>item.categoryId===categoryId&&item.month===month);if(existing) existing.amount=amount; else state.budgets.push({id:createId('budget'),categoryId,month,amount});els.budgetForm.reset();els.budgetMonth.value=getSelectedMonth();els.budgetError.textContent='';renderAll();}
function handleListClicks(event){const button=event.target.closest('button[data-action]');if(!button) return;const action=button.dataset.action;const id=button.dataset.id;if(action==='edit-category'){const category=categoryById(id);if(!category) return;editingCategoryId=id;els.categoryName.value=category.name;els.categoryType.value=category.type;els.categoryIcon.value=category.icon;els.categorySubmitText.textContent='Cập nhật danh mục';els.categoryCancelBtn.hidden=false;els.categoryError.textContent='';}
if(action==='delete-category'){const category=categoryById(id);if(!category) return;const usedInTransactions=state.transactions.some(item=>item.categoryId===id);const usedInBudgets=state.budgets.some(item=>item.categoryId===id);if(usedInTransactions||usedInBudgets){alert('Không thể xóa – danh mục đang được sử dụng bởi giao dịch hoặc hạn mức.');return;}if(confirm(`Bạn có chắc muốn xóa danh mục ${category.name}?`)){state.categories=state.categories.filter(item=>item.id!==id);renderAll();}}
if(action==='edit-transaction'){const tx=state.transactions.find(item=>item.id===id);if(!tx) return;editingTransactionId=id;els.transactionType.value=tx.type;syncCategorySelectors();els.transactionCategory.value=tx.categoryId;els.transactionAmount.value=tx.amount;els.transactionDate.value=tx.date;els.transactionDescription.value=tx.description;els.transactionSubmitText.textContent='Cập nhật giao dịch';els.transactionCancelBtn.hidden=false;els.transactionError.textContent='';}
if(action==='delete-transaction'){const tx=state.transactions.find(item=>item.id===id);const category=tx?categoryById(tx.categoryId):null;if(!tx) return;if(confirm(`Xóa giao dịch ${category?.name||''} - ${formatCurrency(tx.amount)}?`)){state.transactions=state.transactions.filter(item=>item.id!==id);renderAll();}}
if(action==='delete-budget'){const month=button.dataset.month;if(confirm('Xóa hạn mức của danh mục này?')){state.budgets=state.budgets.filter(item=>!(item.categoryId===id&&item.month===month));renderAll();}}}
function attachEvents(){els.categoryForm.addEventListener('submit',handleCategorySubmit);els.transactionForm.addEventListener('submit',handleTransactionSubmit);els.budgetForm.addEventListener('submit',handleBudgetSubmit);els.transactionType.addEventListener('change',syncCategorySelectors);els.categoryType.addEventListener('change',()=>{els.categoryIcon.value=els.categoryType.value==='income'?'💰':'🛒';});els.reportMonth.addEventListener('change',renderAll);els.reportYear.addEventListener('change',renderReports);els.categoryCancelBtn.addEventListener('click',resetCategoryForm);els.transactionCancelBtn.addEventListener('click',resetTransactionForm);document.body.addEventListener('click',handleListClicks);els.resetBtn.addEventListener('click',()=>{if(!confirm('Khôi phục dữ liệu demo mặc định?')) return;state=structuredClone(DEFAULT_STATE);resetCategoryForm();resetTransactionForm();renderAll();});}
function init(){bindElements();els.reportMonth.value='2026-05';els.reportYear.value='2026';els.transactionDate.value=todayISO();syncCategorySelectors();attachEvents();resetCategoryForm();resetTransactionForm();els.reportMonth.value='2026-05';els.reportYear.value='2026';renderAll();}
init();
